export const RoleType = {
  ROLE_SUPERUSER: 'ROLE_SUPERUSER',
  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_MANAGER: 'ROLE_MANAGER',
  ROLE_ASSISTANT: 'ROLE_ASSISTANT',
  ROLE_BROWSER: 'ROLE_BROWSER',
  ROLE_AUTHENTICATED: 'ROLE_AUTHENTICATED',
  ROLE_ANONYMOUS: 'ROLE_ANONYMOUS',
  ROLE_FINANCE: 'ROLE_FINANCE',
  ROLE_INVOICE: 'ROLE_INVOICE',
  ROLE_PRODUCT_MANAGER: 'ROLE_PRODUCT_MANAGER',
  ROLE_EMPLOYEE: 'ROLE_EMPLOYEE',
  ROLE_PURCHASE_APPROVER: 'ROLE_PURCHASE_APPROVER',
  ROLE_BUYER: 'ROLE_BUYER',
  ROLE_ORDER_CLERK: 'ROLE_ORDER_CLERK',
  WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER',
  ROLE_PICKER: 'ROLE_PICKER',
  ROLE_PACKER: 'ROLE_PACKER',
  ROLE_RECEIVER: 'ROLE_RECEIVER',
  ROLE_SHIPMENT_CLERK: 'ROLE_SHIPMENT_CLERK',
  ROLE_STOCKER: 'ROLE_STOCKER',
  ROLE_WORKER: 'ROLE_WORKER',
  ROLE_PHARMACIST: 'ROLE_PHARMACIST',
  ROLE_PHARMACY_TECH: 'ROLE_PHARMACY_TECH',
  ROLE_ORGANIZATION: 'ROLE_ORGANIZATION',
  ROLE_CARRIER: 'ROLE_CARRIER',
  ROLE_SUPPLIER: 'ROLE_SUPPLIER',
  ROLE_MANUFACTURER: 'ROLE_MANUFACTURER',
  ROLE_DISTRIBUTOR: 'ROLE_DISTRIBUTOR',
  ROLE_DONOR: 'ROLE_DONOR',
  ROLE_SHIPPING_AGENT: 'ROLE_SHIPPING_AGENT',
  ROLE_CLEARING_AGENT: 'ROLE_CLEARING_AGENT',
  ROLE_PURCHASER: 'ROLE_PURCHASER',
  ROLE_CUSTOMER: 'ROLE_CUSTOMER',
  ROLE_REQUESTOR: 'ROLE_REQUESTOR',
  ROLE_REQUISITION_APPROVER: 'ROLE_REQUISITION_APPROVER',
} as const;

export type RoleType = typeof RoleType[keyof typeof RoleType];

export interface Role {
  id: string
  uid?: string
  name: string
  roleType: RoleType
  description: string
  usersCount: number
}
